# High quality
profile=high-quality
hwdec=auto-copy
vo=gpu-next

# Fonts
sub-font='Noto Sans'
osd-font='Noto Sans'

# Volume
volume=100
volume-max=200

# Screenshots
screenshot-format=png
screenshot-high-bit-depth=yes
screenshot-png-compression=7
screenshot-directory="~/Pictures/mpv"
screenshot-template="%f-%wH.%wM.%wS.%wT-#%#00n"

# stream quality
ytdl-format=bestvideo[height<=?1080]+bestaudio/best[height<=?1080]/best

