# change prefix to C-a
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# keybinds
bind r source-file ~/.tmux.conf \; display "Config reloaded."
bind c new-window -c "#{pane_current_path}"
bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R
bind -n M-H previous-window
bind -n M-L next-window

# splitting panes
bind | split-window -h -c "#{pane_current_path}"
bind / split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
unbind '"'
unbind %

# resizing panes
bind -r h resize-pane -L 5
bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5

# enable mouse
set -g mouse on

# index from 1
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# vi mode
set -g status-keys vi
setw -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# fix delays
set -sg escape-time 20

# ui
set-option -g status-position top
set -g status-style bg="#44475a",fg="#f8f8f2"
set -g focus-events on
set -g history-limit 50000

