"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](purple)\
$os\
$username\
[](bg:cyan fg:purple)\
$directory\
[](bg:pink fg:cyan)\
$git_branch\
$git_status\
[](bg:green fg:pink)\
$c\
$rust\
$golang\
$nodejs\
$bun\
$php\
$java\
$kotlin\
$haskell\
$python\
[](bg:comment fg:green)\
$time\
[ ](fg:comment)\
$cmd_duration\
$line_break\
$character"""

palette = 'dracula'

[palettes.dracula]
background = "#282a36"
foreground = "#f8f8f2"
purple = "#bd93f9"
cyan = "#8be9fd"
pink = "#ff79c6"
green = "#50fa7b"
yellow = "#f1fa8c"
orange = "#ffb86c"
red = "#ff5555"
comment = "#6272a4"

[os]
disabled = false
style = "bg:purple fg:background"

[os.symbols]
Windows = ""
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
AOSC = ""
Arch = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
show_always = true
style_user = "bg:purple fg:background"
style_root = "bg:red fg:background"
format = '[ $user]($style)'

[username.aliases]
"argoneus" = "argo"

[directory]
style = "bg:cyan fg:background"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:pink"
format = '[[ $symbol $branch ](fg:background bg:pink)]($style)'

[git_status]
style = "bg:pink"
format = '[[($all_status$ahead_behind )](fg:background bg:pink)]($style)'

[nodejs]
symbol = ""
style = "bg:green"
format = '[[ $symbol( $version) ](fg:background bg:green)]($style)'

[bun]
symbol = ""
style = "bg:green"
format = '[[ $symbol( $version) ](fg:background bg:green)]($style)'

[c]
symbol = " "
style = "bg:green"
format = '[[ $symbol( $version) ](fg:background bg:green)]($style)'

[rust]
symbol = ""
style = "bg:green"
format = '[[ $symbol( $version) ](fg:background bg:green)]($style)'

[golang]
symbol = ""
style = "bg:green"
format = '[[ $symbol( $version) ](fg:background bg:green)]($style)'

[php]
symbol = ""
style = "bg:green"
format = '[[ $symbol( $version) ](fg:background bg:green)]($style)'

[java]
symbol = " "
style = "bg:green"
format = '[[ $symbol( $version) ](fg:background bg:green)]($style)'

[kotlin]
symbol = ""
style = "bg:green"
format = '[[ $symbol( $version) ](fg:background bg:green)]($style)'

[haskell]
symbol = ""
style = "bg:green"
format = '[[ $symbol( $version) ](fg:background bg:green)]($style)'

[python]
symbol = ""
style = "bg:green"
format = '[[ $symbol( $version)(\(#$virtualenv\)) ](fg:background bg:green)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:comment"
format = '[[  $time ](fg:background bg:comment)]($style)'

[line_break]
disabled = true

[character]
disabled = false
success_symbol = '[❯](bold fg:green)'
error_symbol = '[❯](bold fg:red)'
vimcmd_symbol = '[❮](bold fg:green)'
vimcmd_replace_one_symbol = '[❮](bold fg:purple)'
vimcmd_replace_symbol = '[❮](bold fg:purple)'
vimcmd_visual_symbol = '[❮](bold fg:yellow)'

[cmd_duration]
show_milliseconds = true
format = " in $duration "
style = "fg:comment"
disabled = false
show_notifications = false
min_time_to_notify = 45000

